[package]
name = "startraders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.9.0"
console = "0.15.0"
indicatif = "0.16.2"
rand = "0.8.4"
rand_pcg = "0.3.1"
itertools = "0.7.8"
