use std;

pub mod instructions {
    pub fn print_instructions() {
        let instructions: &'static str = concat!(
            "   STAR LANES IS A GAME OF INTERSTELLAR TRADING.\n",
            "THE OBJECT OF THE GAME IS TO AMASS THE GREATEST AMOUNT\n",
            "OF MONEY.  THIS IS ACCOMPLISHED BY ESTABLISHING VAST,\n",
            "INTERSTELLAR SHIPPING LANES, AND PURCHASING STOCK IN\n",
            "THE COMPANIES THAT CONTROL THOSE TRADE ROUTES.  DURING\n",
            "THE COURSE OF THE GAME, STOCK APPRECIATES IN VALUE AS\n",
            "THE SHIPPING COMPANIES BECOME LARGER.  ALSO, SMALLER\n",
            "COMPANIES CAN BE MERGED INTO LARGER ONES, AND STOCK\n",
            "IN THE SMALLER FIRM IS CONVERTED INTO STOCK IN THE\n",
            "LARGER ONE AS DESCRIBED BELOW.\n",
            "EACH TURN, THE COMPUTER WILL PRESENT THE PLAYER WITH\n",
            "FIVE PROSPECTIVE SPACES TO OCCUPY ON A 9X12 MATRIX\n",
            "(ROWS 1-9, COLUMNS A-L).  THE PLAYER, AFTER EXAMINING\n",
            "THE MAP OF THE GALAXY TO DECIDE WHICH SPACE HE WISHES\n",
            "TO OCCUPY, RESPONDS WITH THE ROW AND COLUMN OF THAT\n",
            "SPACE, I.E., 7E, 8A, ETC.  THERE ARE FOUR POSSIBLE\n",
            "MOVES A PLAYER CAN MAKE."
        );
        println!("{}", instructions)
    }
}
